 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: dotnet build
       - run: dotnet test /p:CollectCoverage=true /p:CoverletOutput=../../TestResults/ /p:CoverletOutputFormat=opencover
       - run: 
          shell: powershell.exe
          command: .\.circleci\codecov.ps1 -token d77fcebe-30ce-4aa4-bed2-cd9f1ba64e4f -fName .\TestResults\coverage.opencover.xml
